[tool.poetry]
name = "aqc-cli"
version = "1.0.0"
description = "CLI for astroquery modules with autocompletion and multi-language support."
authors = ["inoribea <inoribea@outlook.com>"]
license = "BSD-3-Clause"
readme = "README.md"

packages = [{include = "src"}]

include = [{path = "locales/*/LC_MESSAGES/messages.mo"}]

[tool.poetry.dependencies]
python = ">=3.11"
typer = "^0.15.4"
rich = "^13.5.2"
astropy = "^7.1.0"
babel = "^2.15.0"
requests = "^2.10.0"
astroquery = "^0.4.10"
pyvo = "^1.4.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
snakeviz = "^2.2.0"
polib = "^1.2.0"

[tool.poetry.urls]
Homepage = "https://github.com/inoribea/astroquery-cli"
Documentation = "https://github.com/inoribea/astroquery-cli#readme"
Repository = "https://github.com/inoribea/astroquery-cli"
Issues = "https://github.com/inoribea/astroquery-cli/issues"

[tool.poetry.scripts]
aqc = "src.main:cli"
astrocli = "src.main:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
